### PR TITLE
feat: update to newest ftw-tests-schema

### PR DESCRIPTION
**Pull request by theseion**
- add new `retry_once` option
- add test case for `retry_once`
- make test infrastructure more modular
- improvements to CLI
- support for platform overrides
- removal of deprecated options and obsolete code

### CODE REVIEW

**Comment by fzipi** [comment]
@theseion Looks like we have conflicts on this one...

**Comment by theseion** [comment]
Depends on the new scheme changes.

**Comment by theseion** [comment]
Requires https://github.com/coreruleset/ftw-tests-schema/pull/7

**Comment by theseion** [comment]
I think this is ready. It currently uses a fixed commit from `ftw-tests-schema`, so that we can fix the schema, if necessary, before we tag a new version.

This PR has grown quite a bit because many refactorings came in handy and I opted to adjust the schema on-the-fly where I thought it made sense.

There's a draft PR for CRS where I've made all the necessary changes to support the code here: https://github.com/coreruleset/coreruleset/pull/3369. With that PR, all tests for both nginx and httpd succeed (including all previously disabled and commented tests).

Note that Coraza support will come a bit later with https://github.com/coreruleset/coreruleset/pull/3377.

It would be great if I could also get feedback from @jcchavezs and @christiantreutler-avi on how these changes will affect you.

@jcchavezs Note that I opted to drop the `replace` for `koanf/maps` because it is annoying. If that's a problem for Coraza, let me know.

**Comment by fzipi** [comment]
Well, honestly, is too big to understand cross implications between things. I'll approve and 🤞

**Review by fzipi — APPROVED** [review]

**Pull request merged**
