### PR TITLE
chore: fix goreleaser url homepage after migration

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Update homepage url.

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]

**Comment by fzipi** [comment]
That was quick :D

**Comment by fzipi** [comment]
Something else is broken, because is not giving me the right version:
```
❯ go install github.com/coreruleset/go-ftw@v0.4.0
❯ ./go-ftw --version
12:55AM INF ftw/main: cannot load timezone
ftw version dev
```

**Comment by anuraaga** [comment]
@fzipi version is embedded into the binary as part of gorelease, `go install` can't do it

https://goreleaser.com/cookbooks/using-main.version

**Comment by fzipi** [comment]
Cool, I forgot after some time. Thanks for the pointer.

**Pull request merged**
