### PR TITLE
feat: Introduce multiple value headers

### PR DESCRIPTION
**Pull request by huberts90**
The PR addresses https://github.com/coreruleset/go-ftw/issues/332

### CODE REVIEW

**Comment by fzipi** [comment]
There is a lot of whitespace change in this PR. Is that intended?

**Comment by theseion** [comment]
@huberts90 Please revert the changes to white space. I'll wait with the review until then.

**Comment by fzipi** [comment]
ping @huberts90

**Comment by theseion** [comment]
Ok, thanks for letting us know.

**Pull request closed without merging**
